# server options

set-option -s escape-time 1


# session options

set-option -g base-index 1
set-option -g buffer-limit 20
set -g default-terminal 'screen-256color'
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -g history-limit 5000
set-option -g detach-on-destroy off
set-option -g renumber-windows on
set-option -g mouse on
set-option -g status-keys emacs
set-option -g focus-events on

# colors and appearances

set-option -g status-left-length 18
set-option -g status-left '#{?client_prefix,#[fg=black]#[bg=yellow],#[fg=yellow]#[bg=default]}[%Y-%m-%d %H:%M] #[default]'

set-option -g status-right-length 50
set-option -g status-right-style fg=brightblue,bg=default
set-option -g status-right '[#(~/.local/bin/ip.sh)|#(~/.local/bin/localip.sh)] [#S]'
set-option -g status-style fg=white,bg=default
set-option -g window-status-current-style fg=green,bg=default
set-option -g message-style fg=yellow,bg=default
set-option -g pane-active-border-style none
set-option -g pane-border-style none
set-option -g pane-border-status off
set-option -g window-status-activity-style fg=white,bg=default,underscore

# window options

set-window-option -g automatic-rename on
set-window-option -g mode-keys vi
set-window-option -g monitor-activity on


############ Key Bindings ############
# prefix configuration
unbind C-b
set -g prefix C-j
bind-key C-j send-prefix

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"


# split window and fix path for tmux 1.9
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# synchronize all panes in a window
bind y setw synchronize-panes

# pane movement shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Remap x to avoid confirmation to kill pane
bind-key x run-shell "\
    if tmux has-session -t default 2>/dev/null ; then \
      tmux switch-client -n -t default ; \
  else \
      tmux kill-session -t \"$(tmux display-message -p '#S')\" && \
      tmux detach-client
    fi;"

# Move windows
bind-key S-Left swap-window -t -1\; select-window -t -1
bind-key S-Right swap-window -t +1\; select-window -t +1

# copy mode

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"
